### ISSUE TITLE
Links to apps in the user interface don't consider nonstandard ports

### ISSUE THREAD

**Issue by Pastafarianist** [YunoHost/yunohost-admin#102]
It doesn't look like this is the best place to post a bug about the user interface, but I haven't found a better one.

I am running a Yunohost instance behind a router alongside with another server. The ports on the router are configured in such a way that the other server is the "primary" one (i.e. external ports 80/443 point to the internal ports 80/443 of that server). The internal ports 80/443 of my Yunohost server, however, are associated with external ports 8080/4343. So I can reach my Yunohost server from the outside by pointing my browser to `https://<my-domain-name>.noho.st`.

However, the links in the user interface are broken:

![2015-06-26-00_10_17_selection_001](https://cloud.githubusercontent.com/assets/1315874/8365747/031e8a46-1b98-11e5-8a0a-4c8e89764042.png)

This should point to `https://pastafarianist.noho.st:4343/owncloud` instead.

Please move this issue if I'm posting it in a wrong place.

**Comment by opi** [comment]
User panel regards SSOwat and not yunohost-admin. Please open another issue in https://github.com/Kloadut/SSOwat .
