### ISSUE TITLE
Cannot create a Yunohost user with the same name as a Linux user

### ISSUE THREAD

**Issue by Pastafarianist** [YunoHost/yunohost-admin#103]
I have created a new Linux user using

    useradd -G sudo -m myuser

After that, I could not create a Yunohost user with the name `myuser` because Yunohost complained about there already being a user with that name. There should probably be a way to attach existing users to a Yunohost installation.

**Comment by opi** [comment]
YunoHost users are in fact LDAP users; We cannot have both Unix user and LDAP user with the same name. So I guess there's no way to "attach" existing users to YunoHost users.

**Comment by opi** [comment]
moreover, this is not really a `yunohost-admin` issue. I'm gonna close this issue.
If you think something could be done to address this problem, please open an new issue in Yunohost/yunohost package.
