### ISSUE TITLE
DNS services displayed on Services section.

### ISSUE THREAD

**Issue by M5oul** [YunoHost/yunohost-admin#105]
On Services section, display Dnsmasq if installed and do not display bind9 if not installed.

**Comment by opi** [comment]
yunohost-admin is basically a client for yunohost api.

I guess this issue is more YunoHost/moulinette-yunohost related, see https://github.com/YunoHost/moulinette-yunohost/blob/unstable/data/other/services.yml for services list.

**Comment by M5oul** [comment]
Transfered to https://github.com/YunoHost/moulinette-yunohost/issues/81.
