### ISSUE TITLE
Display labels and app settings in the admin panel

### ISSUE THREAD

**Issue by scith** [YunoHost/yunohost-admin#106]
Hello,
Things get a little bit confusing with multi-instances apps, as their labels and settings are not displayed in the panel. Here is an illustration:

![Confusing panel](http://tof.canardpc.com/preview2/c56af15a-a317-4715-8328-f3923c808d11.jpg)

Would it be possible to at least display the apps labels?
Then in the app detail, display the various settings defined with *sudo yunohost app setting $app*

Thanks

**Comment by M5oul** [comment]
Where do come from/what are `Redirect` apps? In fact it would be great to rename labels for instance for PluXml, cause you need to remember which one you installed first. For instance, one can be called blog and the other family website.

**Comment by scith** [comment]
The Redirect apps are simple apps I use to create an icon associated with an Nginx conf file redirecting elsewhere: https://github.com/scith/redirect_ynh
For example I can redirect to Docker container (which have ports) or external websites.

My PluXml apps do have labels (I see the label in the user panel), but they just don't show in the admin panel.

Thanks

**Comment by M5oul** [comment]
Done with [dev.#41](https://dev.yunohost.org/issues/41).
