### ISSUE TITLE
Bandwidth control

### ISSUE THREAD

**Issue by Thatoo** [YunoHost/yunohost-admin#150]
Hello,

Would it be possible in the admin control panel of yunohost to control bandwidth of our yunohost?
It would be great to be able to limit global bandwidth of our yunohost. For example, someone who has a limited DSL access of 2Mb/s could limit his yunohost bandwidth to 1Mb/s or 1.5Mb/s.
And then, it would be great also to be able to allocate bandwidth to each app as a percentage of this global bandwidth limitation.

What do you think?

Thank you all for your great work. I'm new in this world and so far so good (except this bandwidth little problem, I guess I'll have to uninstall searx)

Thatoo

**Comment by M5oul** [comment]
Could you [move this ticket to our bug tracker](https://dev.yunohost.org/projects/yunohost/issues/new).
We don't use GitHub bugtracker.
