### ISSUE TITLE
Yunohost v2 apps install error on debian 7

### ISSUE THREAD

**Issue by mikamboo** [YunoHost/yunohost-admin#68]
After installation of ynh on a clean debian 7 and post install succès i had some troubles with apps installation from web administration page. 

After a long time after install (or uninstall) request i get the following error message: **"504 Gateway Time-out nginx"**.

When i return to app liste it seems to be intalled but when à lauch it doesn't work properly.

I tried to install in command line (moulinette tool) and installation works perfectly.

**Comment by opi** [comment]
debian 7 is not supported anymore
