### ISSUE TITLE
Associer un label à chaque port ouvert / Associate a label to each open port

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost/yunohost-admin#77]
Ajouter un label aux ports ouverts dans l'interface admin afin de les associer rapidement à l'app ou le service concerné.

Le label serait renseigné par le script d'install de chaque app lors de l'appel de sudo yunohost app checkport.

Cela pose toutefois la question du stockage de l'information.

---

Add a label to open ports in the admin interface to quickly associate the app or service involved.

The label would be completed by the install script for each app when calling sudo yunohost app checkport.

However, this raises the question of storage of information.

**Comment by alexAubin** [comment]
Moved to https://dev.yunohost.org/issues/862
