### ISSUE TITLE
Add a button redirectiong toward user interface.

### ISSUE THREAD

**Issue by M5oul** [YunoHost/yunohost-admin#85]
It could be great to have a button visible everywhere where are on the admin interface when log-in, redirectiong toward user interface `/yunohost/sso`. This button could be placed bettwen the YunoHost logo and the logout logo. We could aslo add a button on the admin interface when log-out? People are lost sometimes after installation. To be discuss.

**Comment by opi** [comment]
Good idea.

I guess we just need to add a "User interface" link inside a footer tag, in https://github.com/YunoHost/yunohost-admin/blob/unstable/src%2Findex.html
