### ISSUE TITLE
Update of phpmyadmin via webinterface failed but worked with cli

### ISSUE THREAD

**Issue by polytan02** [YunoHost/yunohost-admin#86]
Hi,

Today I went to see if there was any update of the app installed via the YnH web interface.
Indeed, phpmyadmin needed an update.

I click on the buttoned and it failed.
To be noted that it worked perfectly using the command line tools. 

The logs are available here :
https://www.mcgva.ovh/zerobin/?85a683c15675185e#h7owFJoa8vStb0vwxP3eh+RXpGHSd0lHwA195PdP1JY=

**Comment by opi** [comment]
@polytan02 still relevant ?

**Comment by polytan02** [comment]
I don't think so.
