### ISSUE TITLE
Login Bug Yunohost API

### ISSUE THREAD

**Issue by Blamao** [YunoHost/yunohost-admin#89]
Yunohost creates a SSOwAuthExpire cookie if you log with an upper case letter in your login (for example logging in with Blamao instead of blamao).
Then this error is displayed: 500 Internal Server Error Nginx

**Comment by opi** [comment]
this issue is SSOWat related (https://github.com/Kloadut/SSOwat), and I guess it solved by now, but I need @Kloadut to confirm.

**Comment by Kloadut** [comment]
Yes it is solved :-)
Just upgrade your ssowat package and it should be ok
