### ISSUE TITLE
/usr/share/yunohost/admin/ is owned by www-data

### ISSUE THREAD

**Issue by julienmalik** [YunoHost/yunohost-admin#91]
It should be root:root

**Comment by opi** [comment]
I have no idea where to define these ownership

**Comment by opi** [comment]
Addressed by https://github.com/YunoHost/yunohost-admin/pull/156 cc @julienmalik

**Comment by alexAubin** [comment]
Moved to redmine : https://dev.yunohost.org/issues/857
