### ISSUE TITLE
Do not clear the slide when form is invalid

### ISSUE THREAD

**Issue by jeromelebleu** [YunoHost/yunohost-admin#92]
Due to https://github.com/YunoHost/yunohost-admin/blob/unstable/src/js/app.js#L189, forms which are invalid from the moulinette side - e.g. create a user with an invalid mailbox quota - are cleaned on each submission. It would be better and more practical to keep the form values until it is successfully submitted.

**Comment by Psycojoker** [comment]
+1 that's one especially annoying bug that will drive users frustrated and will give them a bad feeling about the usability.

It's probably as frustrated to live as to fix it sadly.

**Comment by M5oul** [comment]
See https://dev.yunohost.org/issues/45.
