### ISSUE TITLE
Show moulinette cli equivalent

### ISSUE THREAD

**Issue by julienmalik** [YunoHost/yunohost-admin#93]
When doing something in the admin ui, show the equivalent yunohost cli command.
Also log them in the yunohost log file.

This would help new comers to become familiar with the moulinette.

**Comment by opi** [comment]
Don't understand the "Also log them in the yunohost log file."

But showing the cli command corresponding to the web-admin action is a lovely idea !

**Comment by julienmalik** [comment]
I meant having them written in the /var/log/yunohost-something.log but it might be a feature request for moulinette.

**Comment by opi** [comment]
because ynh-moulinette is supposed to log everything, at least in the unstable version, and because ynh-admin is just a client for this API, I guess every web action will be logged as any regular cli action.

Am I right @jeromelebleu ?

**Comment by julienmalik** [comment]
The idea is to log a real command (that can be copy/pasted in a shell) for every command, even if they come from the API.

**Comment by jeromelebleu** [comment]
@opi: yep you're right, each call to the moulinette is logged - except the messages for the moment- for each interface and in a separate file - i.e. API calls are logged in /var/log/yunohost/yunohost-api.log.

**Comment by alexAubin** [comment]
Moved to https://dev.yunohost.org/issues/863
