### ISSUE TITLE
[bug][2.1.5] Can't install several instances of multisite apps 

### ISSUE THREAD

**Issue by zamentur** [YunoHost/yunohost-admin#94]
Hi,

On yunohost-admin/testing 2.1.5, I can't install several instances of multisite apps, I do a video capture to explain that:
https://grimaud.me/fichier/index.php/s/qNiGmYnD81gWf04

Like in the video, when I try to install the second time the app I get the page of the first instance. It should give me the install page.

Thanks for this new version.

**Comment by opi** [comment]
Is this issue fixed now with bf35327ae5244587b2ea4b57e4379e39beb9a65f ?

**Comment by opi** [comment]
Fixed
