### ISSUE TITLE
[bug][2.1.5] Link broken on security alert

### ISSUE THREAD

**Issue by zamentur** [YunoHost/yunohost-admin#95]
Hi,

On yunohost-admin/testing 2.1.5, I have several broken links "En savoir plus" on security alert.
This is because the links are relative but this is link relative to the forum.yunohost.org not to the yunohost instance of the user.

exemple: https://grimaud.me/fichier/index.php/s/Um2kisHGx1y9YMJ

Thanks for this new version.

**Comment by opi** [comment]
Fixed by 21be86fc055a91ab51fd5de986aed4fd30b07b42
