### ISSUE TITLE
[bug][2.1.5] Close IPv6 firewall rules close IPV4 too

### ISSUE THREAD

**Issue by zamentur** [YunoHost/yunohost-admin#96]
Hi,
On yunohost-admin/testing 2.1.5, when I close the ipv6 for a port it seems that the ipv4 is closed too.

exemple: https://grimaud.me/fichier/index.php/s/8gmS71z0bHuD0uF

Thanks for this new version.

**Comment by zamentur** [comment]
It's due to that http://stackoverflow.com/questions/15088955/how-to-pass-data-in-the-ajax-delete-request-other-than-headers

**Comment by jeromelebleu** [comment]
Thanks for the bug report! It was due to some changes in the firewall actions that I didn't apply on the yunohost-admin.
